# Generated by Django 2.2.6 on 2019-12-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(null=True)),
                ('replyStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=60)),
                ('contactPhone', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('pic', models.FileField(upload_to='uploads/events/%Y/%m/%d/')),
                ('eventStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HaederSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('pic', models.FileField(upload_to='uploads/slider/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('pic', models.FileField(upload_to='uploads/membersPhoto/%Y/%m/%d/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ourTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('JobTitle', models.CharField(max_length=60)),
                ('pic', models.FileField(upload_to='uploads/ourTeam/%Y/%m/%d/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('fullName', models.CharField(max_length=60)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('activeUser', models.BooleanField(default=0)),
                ('Profilephoto', models.FileField(upload_to='uploads/regPhotos/%Y/%m/%d/')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('lastModifiedDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSubscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('startTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('pic', models.FileField(upload_to='uploads/events/%Y/%m/%d/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eLearn.Events')),
            ],
        ),
    ]
